### ISSUE TITLE
@ShardingTransactionType(TransactionType.XA)不生效

### ISSUE THREAD

**Issue by itGuoYong** [OpenSharding/shardingsphere-spi-impl-example#1]
在“transaction-xa-spring-boot-example”这项目中，执行例子代码，发现分布式事务没生效，在抛出异常后，数据还是落地到数据库中。

我在网上找了一个基于3.X的demo。@ShardingTransactionType(TransactionType.XA)这个注解是生效的，但是在4.X的项目中，没有生效。
我查阅了3.X的代码，是对这个注解有进行切面处理，但是4.X没有处理这注解。 不知是否4.X取消了这注解的作用？

**Comment by cherrylzhao** [comment]
@ShardingTransactionType aspect have been moved to `https://github.com/OpenSharding/shardingsphere-spi-impl` you should install it by yourself.
